# Generated by Django 4.2.7 on 2023-11-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
    ]
