# Generated by Django 4.2.7 on 2023-11-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=20)),
                ('km', models.CharField(max_length=20)),
                ('preco', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('cambio', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
            ],
        ),
    ]
