# Generated by Django 4.2.7 on 2023-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=20)),
                ('duracao', models.EmailField(max_length=254)),
                ('professor', models.CharField(max_length=15)),
                ('codigo', models.CharField(default='', max_length=100)),
                ('setor', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
